deploy:
  stage: deploy
  image: samuelsantos/generate-diagrams-as-code:latest
  tags: 
    - master
  script:
    - DIAGRAM_FILE=diagram-istio.py
    - diagram.py --name diagrams-istio.py samuelsantos/generate-diagrams-as-code    
