generate_diagram:
  stage: build
  image: samuelsantos/generate-diagrams-as-code:latest
  script:
    - DIAGRAM_FILE=diagram-istio.py
    - python $DIAGRAM_FILE
  artifacts:
    paths: 
      - diagram-istio.png  
  only: 
    - master

