name: Diagram.py to PNG

on:
  push:
    branches: 
      - master
      - dev
    tags:
       - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    container: samuelsantos/generate-diagrams-as-code:latest
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Convert Py to PNG
        run: python diagram-istio.py
      - name: Upload PNG to the workflow
        uses: actions/upload-artifact@v2
        with:
          name: diagram-istio
          path: diagram-istio.png
